### ISSUE TITLE
Compatability issue.

### ISSUE THREAD

**Issue by xy172** [kenigvovan/cancrops_7#1]
For some reason having https://mods.vintagestory.at/absoluteprospecting installed makes your mod attempt to load the xskills compatability and then errors. If you need anything else feel free to ask. I will also post about this on their mod page incase it is not your side but theirs.

14.8.2024 11:18:29 [Error] [cancrops] An exception was thrown when trying to start the mod:
14.8.2024 11:18:29 [Error] [cancrops] Exception: Could not load file or assembly 'xskills, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at cancrops.src.compat.xskills.XSkillsCompat.StartServerSide(ICoreServerAPI api)
   at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 660
14.8.2024 11:18:29 [Error] Failed to start system cancrops.src.compat.xskills.XSkillsCompat

**Comment by xy172** [comment]
I did test with just those two mods enabled and the issue persists.

**Comment by kenigvovan** [comment]
this is just the way compatibility is handled without using separated mod for every other mod. If game loads and all installed mods then everything is ok

**Comment by xy172** [comment]
The singleplayer server does not load, I thought that was the crash triggering error.
 I will attach the full logs.
[server-audit.txt](https://github.com/user-attachments/files/16616954/server-audit.txt)
[server-build.txt](https://github.com/user-attachments/files/16616955/server-build.txt)
[server-chat.txt](https://github.com/user-attachments/files/16616956/server-chat.txt)
[server-debug.txt](https://github.com/user-attachments/files/16616957/server-debug.txt)
[server-event.txt](https://github.com/user-attachments/files/16616958/server-event.txt)
[server-main.txt](https://github.com/user-attachments/files/16616959/server-main.txt)
[server-storyevent.txt](https://github.com/user-attachments/files/16616961/server-storyevent.txt)

**Comment by xy172** [comment]
Hmm it only seems to happen on single player creative worlds. Weird

**Comment by kenigvovan** [comment]
try to remove cancrops and start the world with absoluteprospecting only

**Comment by xy172** [comment]
I see, sorry to post the issue here when its that mod alone. The error happening right before the crash made me think it was some compatibility issue. Ill close this and move to the other issue I linked. Thanks for the help!
